Fix the logic for the dontneed_reasons variables
cmu-delphi/covidcast-indicators pull request #1061
Opened 2021-05-21 01:21 UTC by davidkretch

Hello @nmdefries, sorry for the delayed update.

### Description
* Fix the logic for the COVID Symptom Survey `dontneed_reason` variables.
* Define the wave of a given dataset based on the latest wave in the data; without this, the contingency tables wouldn't run.

### Changelog

In `facebook/delphiFacebook/R/contingency_variables.R`:

* Fix the logic for the `dontneed_reason` variables, which should depend only on respondents to V5a, V5b, and V5c. Previously, these variables also included respondents to V5d.
* Use the latest wave in the data to determine whether to generate old or new variables. **I am not sure how you want to treat these.** Without this, `create_derivative_columns` did not work for me. In this function there is some code to generate variables based on `wave`, which is not created or passed in anywhere.

2021-05-21 15:38 UTC, nmdefries requested changes
Thanks!

2021-05-22 03:23 UTC, davidkretch commented on facebook/delphiFacebook/R/contingency_variables.R
> +    )
Addressed. Logic looks right to me and I checked the new results and the new results match the previous.

2021-05-24 22:47 UTC, nmdefries commented on facebook/delphiFacebook/R/contingency_variables.R
> +    )
>  I checked that the new results match the previous

Perfect, thank you!

2021-05-24 22:49 UTC, nmdefries approved these changes
Looks good!

@capnrefsmmat can you merge?

2021-05-26 14:03 UTC, merged

2021-05-26 14:03 UTC, krivard commented
😛