CHNG Flu Signal
cmu-delphi/covidcast-indicators pull request #1375
Opened 2021-11-24 00:05 UTC by rumackaaron

### Description
Add outpatient CHNG flu signal. This signal is analogous to the cli and covid signals already produced from CHNG data. The numerator is ICD codes J09*-J11* and we have already been receiving these aggregated counts from CHNG.

### Changelog
Itemize code/test/documentation changes and files added/removed.
- `load_data.py` - Use `load_flu_data()` to create Pandas df with numerator specified as above and denominator as total outpatient visits.
- Other files were changed as necessary to create the signal but no modifications to the smoothing, adjustments, etc. were made.

### Fixes 
- Implements #1374

### Notes
The pseudocount addition creates a weekday problem. Over the summer, numerators are basically zero for several states while the denominators are smaller on weekends. Adding the pseudocount of 0.5 to the numerator means that there is a spike in the ratio on weekends because the signal value on a weekend is 0.5/(weekend total) and on a weekday is 0.5/(weekday total). This problem is present whether or not weekday adjustment is done, since the weekday adjustment only corrects the numerators which will remain at 0 in these states during the summer.

2021-11-29 14:53 UTC, krivard requested changes
Missing tests; also possible unnecessary code duplication

2021-11-29 14:53 UTC, krivard commented on changehc/delphi_changehc/download_ftp_files.py
> +def download_flu(filedate, out_path, ftp_conn):
What's the difference between download_flu, download_covid, and download_cli? If they're identical I'd rather we not copy-paste.

2021-11-30 21:27 UTC, rumackaaron commented
Unduplicated code and added tests

2021-12-02 16:15 UTC, krivard approved these changes
👍 

I'm changing the function name but only because I'm insufferable

2021-12-02 16:15 UTC, krivard commented on changehc/delphi_changehc/download_ftp_files.py
>  def download_covid(filedate, out_path, ftp_conn):
```suggestion
def download_counts(filedate, out_path, ftp_conn):
```

2021-12-02 16:15 UTC, krivard commented on changehc/delphi_changehc/run.py
> +from .download_ftp_files import download_covid
```suggestion
from .download_ftp_files import download_counts
```

2021-12-02 16:15 UTC, krivard commented on changehc/delphi_changehc/run.py
> +        download_covid(filedate, params["indicator"]["input_cache_dir"], params["indicator"]["ftp_conn"])
```suggestion
        download_counts(filedate, params["indicator"]["input_cache_dir"], params["indicator"]["ftp_conn"])
```

2021-12-02 16:21 UTC, merged