[CTIS] QSF differ to report new and old question IDs
cmu-delphi/covidcast-indicators pull request #1553
Opened 2022-03-09 18:18 UTC by nmdefries

### Description
Some code cleanup and formatting. Output both new and old QIDs for each question, in case the QID changed.

### Changelog
- `qsf-tools/qsf-differ.R`

2022-03-09 21:24 UTC, capnrefsmmat requested changes
One doc fix and then I think we're good

2022-03-09 21:24 UTC, capnrefsmmat commented on facebook/qsf-tools/qsf-differ.R
> +                           old_reference_qsf, new_reference_qsf) {
I think the documentation block for this function will need to be updated with the new argument names

2022-03-10 13:07 UTC, capnrefsmmat approved these changes

2022-03-10 15:21 UTC, nmdefries commented
@krivard this is ready to merge

2022-03-10 15:28 UTC, merged