Covidcast-indicators version logging and workflow
cmu-delphi/covidcast-indicators pull request #1736
Opened 2022-12-09 21:39 UTC by M5Skid

### Description
Adds logging for indicator name and covidcast-indicators repository version when started by delphi_utils.runner. Workflow populates version.cfg in indicator directories with current version (same as .bumpversion.cfg), and runner will check this file on individual indicator startup.
- Removed decommissioned indicators from the workflow 

### Changelog

create-release.yml
- copy covidcast-indicators version to indicator directories

runner.py
- check version.cfg for version info, output indicator name and version

### Fixes 
- Fixes #1702

2022-12-12 16:09 UTC, krivard requested changes
Great first pass! This functionality seems like something we should include in unit tests, which would require some refactoring.

We should fix the file I/O before merging but leave tests as future work; I'll open an issue for that.

2022-12-12 16:45 UTC, M5Skid commented on _delphi_utils_python/delphi_utils/runner.py
> +                current_version = current_version.replace("current_version = ", "")
Thanks for the additional resources! I think this is a good correction.

2022-12-12 21:49 UTC, krivard approved these changes
👍

2022-12-12 21:52 UTC, krivard commented
Note to self: this affects Runner, so there's a tiny but nonzero chance of hosing our entire stable of indicators. To be safe, merge this on a tuesday evening, then wednesday make the staging server run all the indicators and make sure there are no mishaps before releasing to prod.

2022-12-13 19:02 UTC, korlaxxalrok commented
@krivard @M5Skid

I think we called this out earlier as an eventual necessity:

Because the new indicator versioning process is happening in the release workflow that ultimately generates a PR against prod, we are going to need to set up an additional build+deploy step in Jenkins to create a new set of indicator targzs built from prod that will contain the version file.

2022-12-13 19:10 UTC, korlaxxalrok approved these changes
Looks good 👍 💥

2022-12-13 21:01 UTC, krivard commented
Oh shoot you're failing the linter check in runner.py -- take a look? I'll be able to pick it up an hour to fix and merge if you haven't found it by then.

2022-12-13 21:23 UTC, M5Skid commented
It looks like linter is having issues with some white spaces. I took the spaces out and will try to run a quick local test with linter before resubmitting the PR.

2022-12-13 21:44 UTC, merged