Add NSSP secondary source
cmu-delphi/covidcast-indicators pull request #2074
Opened 2024-11-06 22:34 UTC by minhkhul

### Description
Context: https://delphi-org.slack.com/archives/C0130CSQRN3/p1730476295781409
Basically we're adding 4 signals from [this](https://data.cdc.gov/Public-Health-Surveillance/2023-Respiratory-Virus-Response-NSSP-Emergency-Dep/7mra-9cq9/data_preview) secondary nssp source dataset. They report essentially the same data as the [main dataset](https://data.cdc.gov/Public-Health-Surveillance/NSSP-Emergency-Department-Visit-Trajectories-by-St/rdmq-nq56/data_preview), but only available at state level and above. However, it appears this secondary source updates quicker than the main source recently. 

- [ ] need name approval from Roni
- [ ] adjust tests
- [ ] source stash? (different source -> different stash?)

### Changelog
Add 4 signals: `pct_ed_visits_covid_secondary`, `pct_ed_visits_influenza_secondary`, `pct_ed_visits_rsv_secondary`, `pct_ed_visits_combined_secondary` to nssp.

### Associated Issue(s) 
- Addresses #2073

2024-11-07 17:18 UTC, aysim319 requested changes

2024-11-07 17:26 UTC, minhkhul commented on nssp/delphi_nssp/run.py
yup the weekly stuff is a bug. I'll fix that in a moment. 
The rounded shortness is from source. Definitely nees a note in the issue + readme changes for that.

2024-11-07 19:53 UTC, minhkhul commented on nssp/tests/test_pull.py
> +        mock_client.get.assert_any_call("7mra-9cq9", limit=50000, offset=0)
The schema of the 2 sources are actually quite different, hence the discrepancy in the columns, and also why I didn't use the same test data file. But I like what you said about making tests for the 2 sources to get data from the same time frame, so Imma do that.

2024-11-08 17:26 UTC, nolangormley reviewed
Some small nitpicks, but overall looks good!

2024-11-08 17:26 UTC, nolangormley commented on nssp/delphi_nssp/pull.py
> +        df_ervisits = df_ervisits.astype(SECONDARY_TYPE_DICT)
[nitpick] You can specify column names and data types on load with Pandas. That might be better than the renaming and casting here.

2024-11-08 17:26 UTC, nolangormley commented on nssp/delphi_nssp/run.py
> +            continue
Think it would be worth it to log signals that are empty during the runs, or would that get too noisy?

2024-11-11 16:30 UTC, aysim319 commented on nssp/DETAILS.md
> +There are 2 sources we grab data from for nssp:
Mention that there are some difference that's significant; I actually got 4% of the data having more that .1 difference and I would also mention this to logan/daniel/etc as an fyi

2024-11-11 16:32 UTC, aysim319 approved these changes
Add the comment in the details that there are some difference; in the sample run there were 4% that was more than .1 difference and it should be good.

2024-11-17 23:10 UTC, merged