Fix JHU's fips-population source file
cmu-delphi/covidcast-indicators pull request #301
Opened 2020-10-08 21:59 UTC by dshemetov

* use geocode utility source file and remove old static source file
* update tests
* update validation notebook to verify prop signals in NYC

2020-10-09 13:35 UTC, krivard commented
It could've gone either way, but I switched the base to `deploy-jhu` because this PR primarily concerns the JHU indicator. Once we merge it, we'll propagate the changes to `main`.

2020-10-13 15:38 UTC, sarah-colq commented on testing_utils/indicator_validation.ipynb
> +      "text/plain": "<Figure size 1152x432 with 1 Axes>",
Should we be able to see the remote line or are they identical here?  I cannot see the remote line on any of the new charts.

2020-10-13 15:38 UTC, sarah-colq requested changes
Please check the charts in the python notebook.  Otherwise, looks good! :)

2020-10-13 19:14 UTC, dshemetov commented
That notebook isn't really supposed to be tracked. It was meant to be a template, but I kept working in the template and committed changes. I've reverted it back to its template version and renamed it accordingly.

2020-10-13 19:30 UTC, krivard approved these changes

2020-10-13 19:30 UTC, merged