Update safegraph docstrings to pass pydocstyle
cmu-delphi/covidcast-indicators pull request #373
Opened 2020-10-27 00:51 UTC by chinandrew

Summary of changes:
- Update docstrings so they pass the pydocstyle linter, which checks against most of PEP257

2020-10-28 13:14 UTC, sgsmob requested changes
Looks good minus the one comment.

2020-10-28 13:14 UTC, sgsmob commented on safegraph/delphi_safegraph/process.py
> +    Assumes each data frame has _only_ one
Combine into single line

2020-10-28 15:22 UTC, chinandrew commented on safegraph/delphi_safegraph/process.py
> +    Assumes each data frame has _only_ one
Done

2020-10-28 15:24 UTC, sgsmob approved these changes

2020-11-05 15:04 UTC, krivard commented
@chinandrew I think this ran afoul of #368

2020-11-05 17:18 UTC, chinandrew commented
> @chinandrew I think this ran afoul of #368

resolved

2020-11-05 21:51 UTC, merged