Check for duplicate rows
cmu-delphi/covidcast-indicators pull request #576
Opened 2020-11-23 20:03 UTC by JedGrabman

### Description
New validation check raises warning if files contain multiple copies of an identical row (which indicates possible data integrity issues)

### Changelog
- validate.py - Added `check_duplicate_rows` and related calls
- test_checks.py - Added tests for `check_duplicate_rows` in validate.py
- PLANS.md - Remove duplicate rows task from list

### Fixes 
- Fixes "check for duplicate rows" task in PLANS.md (no associated Github issue)

2020-11-23 20:04 UTC, JedGrabman commented
@nmdefries for review.

2020-11-24 16:11 UTC, nmdefries requested changes
This works when I run the validator, but tests don't pass due to missing params.

2020-11-25 19:06 UTC, JedGrabman commented on validator/PLANS.md
> -* Check for duplicate rows
Done

2020-11-25 19:08 UTC, JedGrabman commented on validator/tests/test_checks.py
> +    params = {}
Copied `params` from another test, see if that resolves it. If it's possible to set reasonable defaults for any of these values, we should add that to our TODOs.

2020-12-01 14:53 UTC, nmdefries approved these changes

2020-12-01 15:06 UTC, nmdefries commented on validator/tests/test_checks.py
> +    params = {}
That's a thought. Initially I intentionally didn't define defaults for a small set of params that greatly change the outcome of running this package (what dataset being used, dates, etc).

2020-12-02 22:00 UTC, krivard commented
Should this go into `main` or the branch?

2020-12-03 14:33 UTC, nmdefries commented
@krivard This should go into main; I changed the base branch to reflect that.

2020-12-03 15:37 UTC, merged