Add skeleton for HHS facilities indicator
cmu-delphi/covidcast-indicators pull request #626
Opened 2020-12-10 22:30 UTC by chinandrew

### Description
Add the template and some placeholder information for the new HHS indicator. No code runs yet.

### Changelog
Itemize code/test/documentation changes and files added/removed.
- Add placeholder test and constants (exact signals are still TBD)
- Add some commented pseudocode for what will run
- Comment out some relevant imports and add to setup.py, also mainly as a placeholder
- Enable CI on this folder

### Fixes 
- Fixes #(issue)

2020-12-10 22:59 UTC, krivard requested changes
one of these days we'll write a script to fill in placeholders

2020-12-10 22:59 UTC, krivard commented on hhs_facilities/delphi_hhs_facilities/__init__.py
> +"""Module to pull and clean indicators from the XXXXX source.
Fill in placeholders

2020-12-10 22:59 UTC, krivard commented on hhs_facilities/delphi_hhs_facilities/__main__.py
> +This file indicates that calling the module (`python -m MODULE_NAME`) will
Fill in placeholders

2020-12-10 22:59 UTC, krivard commented on hhs_facilities/delphi_hhs_facilities/run.py
> +when the module is run with `python -m MODULE_NAME`.
Fill in placeholders

2020-12-10 22:59 UTC, krivard commented on hhs_facilities/setup.py
> +        "Programming Language :: Python :: 3.7",
This should by 3.8 (gotta fix that template someday)

2020-12-10 22:59 UTC, krivard commented on hhs_facilities/README.md
> +env/bin/python -m delphi_NAME
Fill in placeholders

2020-12-10 22:59 UTC, krivard commented on hhs_facilities/README.md
> +(cd tests && ../env/bin/pytest <your_test>.py --cov=delphi_NAME --cov-report=term-missing)
Fill in placeholders

2020-12-10 23:10 UTC, chinandrew commented
Thanks for pointing all these out, I've updated them now

2020-12-11 21:02 UTC, krivard approved these changes
🎉

2020-12-11 21:02 UTC, merged