Add HHS and Nation to combo cases
cmu-delphi/covidcast-indicators pull request #669
Opened 2020-12-29 03:45 UTC by chinandrew

### Description
This ones a bit tricky since the signal combines usafacts and JHU. What I ended up doing was having hhs and nation process as if they were fips and then geomap them to the corresponding regions at the end. One thing to note was that the state and county values dont sum up to the same thing, not sure if thats expected due to JHU/USAFacts processing):

```
In [5]: df = pd.read_csv("receiving/20201218_county_confirmed_cumulative_num.csv")                                                                                   

In [6]: df.val.sum()                                                                                                                                                 
Out[6]: 17103973.0

In [7]: df = pd.read_csv("receiving/20201218_state_confirmed_cumulative_num.csv")                                                                                    

In [8]: df.val.sum()                                                                                                                                                 
Out[8]: 17167997
```

### Changelog
Itemize code/test/documentation changes and files added/removed.
- Add handling of hhs and nation conversion by adding having them retrieve the fips data and then geomap at the end. Update constants.

### Fixes 
- Fixes #(issue)

2021-01-04 16:32 UTC, krivard requested changes
Add test for hhs or nation just to verify logic works as designed

2021-01-04 16:32 UTC, krivard commented on combo_cases_and_deaths/delphi_combo_cases_and_deaths/run.py
> +    geo_to_fetch = "county" if geo in ["county", "hhs", "nation"] else geo
"county" is not needed in that list. I have a slight impulse to extract to a constant set but it's probably more readable as is.

2021-01-04 21:45 UTC, krivard commented
+tests?

2021-01-04 21:54 UTC, chinandrew commented
> +tests?

Just got around to updating them. Also ran the indicator and eyeballed the output files.

2021-01-05 14:54 UTC, krivard approved these changes
xlnt

2021-01-05 14:54 UTC, merged